# Generated by Django 4.0 on 2022-02-07 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_friendrequestfield'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FriendRequestField',
            new_name='FriendRequest',
        ),
    ]
