# Generated by Django 4.0 on 2022-02-10 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('blogapp', '0004_feedback_remove_post_likes_post_feedbacks_post_tags_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('user', 'post')},
        ),
    ]
